"""
Report Writer — generates structured Markdown review reports.

Takes a ReviewReport (collection of Annotations across dimensions)
and renders it as a navigable, human-readable Markdown document.

Output follows the format from CLAUDE.md: Location → Severity → What → Why.
NO suggested fixes. The human decides what to do.
"""

import os
from datetime import datetime

from src.annotation import Annotation, ReviewReport, Severity
from src.reviewers import DIMENSION_NAMES

# Severity display
_SEVERITY_ICON = {
    Severity.HIGH: "🔴",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
}


def _format_location(loc) -> str:
    """Format a Location object into a readable string."""
    parts = []
    if loc.section:
        parts.append(f"Section: {loc.section}")
    if loc.paragraph:
        parts.append(f"Paragraph {loc.paragraph}")
    if loc.line_start:
        if loc.line_end and loc.line_end != loc.line_start:
            parts.append(f"Lines {loc.line_start}–{loc.line_end}")
        else:
            parts.append(f"Line {loc.line_start}")

    return " | ".join(parts) if parts else "Location not specified"


def render_annotation(annotation: Annotation) -> str:
    """Render a single annotation as a Markdown block."""
    sev_icon = _SEVERITY_ICON.get(annotation.severity, "⚪")
    location_str = _format_location(annotation.location)

    lines = [
        f"### {sev_icon} {annotation.title}",
        "",
        f"**Location:** {location_str}",
        f"**Severity:** {annotation.severity.value.upper()}",
        f"**Category:** {annotation.category or 'general'}",
        "",
        "**What:**",
        f"{annotation.what}",
        "",
    ]

    if annotation.why:
        lines.extend([
            "**Why it matters:**",
            f"{annotation.why}",
            "",
        ])

    if annotation.location.quoted_text:
        lines.extend([
            "<details>",
            "<summary>📄 Context</summary>",
            "",
            "```",
            annotation.location.quoted_text.strip(),
            "```",
            "</details>",
            "",
        ])

    lines.append("---")
    return "\n".join(lines)


def render_report(report: ReviewReport, paper_title: str = "") -> str:
    """Render a complete ReviewReport as a Markdown document.

    Returns the full Markdown string, ready to write to a .md file.
    """
    title = paper_title or report.paper_title or os.path.basename(report.paper_path)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    doc: list[str] = [
        f"# 📄 Paper Review Report",
        "",
        f"**Paper:** {title}",
        f"**Path:** `{report.paper_path}`",
        f"**Generated:** {now}",
        f"**Dimensions reviewed:** {', '.join(report.dimensions_reviewed)}",
        "",
        "---",
        "",
    ]

    # ── Summary ──
    doc.append("## 📊 Summary")
    doc.append("")

    counts = report.count_by_dimension()
    sev_counts = report.count_by_severity()

    doc.append("| Dimension | Annotations | 🔴 High | 🟡 Medium | 🟢 Low |")
    doc.append("|-----------|-------------|---------|-----------|--------|")

    for dim in report.dimensions_reviewed:
        dim_name = DIMENSION_NAMES.get(dim, dim)
        dim_anns = report.by_dimension(dim)
        high = sum(1 for a in dim_anns if a.severity == Severity.HIGH)
        med = sum(1 for a in dim_anns if a.severity == Severity.MEDIUM)
        low = sum(1 for a in dim_anns if a.severity == Severity.LOW)
        doc.append(f"| {dim_name} | {len(dim_anns)} | {high} | {med} | {low} |")

    doc.append("| **Total** | **{}** | **{}** | **{}** | **{}** |".format(
        report.total_annotations,
        sev_counts.get("high", 0),
        sev_counts.get("medium", 0),
        sev_counts.get("low", 0),
    ))
    doc.append("")

    # ── Per-Dimension Findings ──
    doc.append("---")
    doc.append("")
    doc.append("## 🔍 Detailed Findings")
    doc.append("")

    for dim in report.dimensions_reviewed:
        dim_name = DIMENSION_NAMES.get(dim, dim)
        dim_anns = report.by_dimension(dim)

        doc.append(f"### {dim_name} ({len(dim_anns)} findings)")
        doc.append("")

        if not dim_anns:
            doc.append("✅ No issues found.")
            doc.append("")
            continue

        # Sort by severity: high → medium → low
        dim_anns.sort(key=lambda a: (
            0 if a.severity == Severity.HIGH else
            1 if a.severity == Severity.MEDIUM else 2
        ))

        for annotation in dim_anns:
            doc.append(render_annotation(annotation))

        doc.append("")

    # ── Footer ──
    doc.extend([
        "---",
        "",
        "*Report generated by Paper Human-Review Assistant.*",
        "*AI annotates, humans decide. No text was modified by this tool.*",
    ])

    return "\n".join(doc)


def write_report(report: ReviewReport, output_dir: str = "output") -> str:
    """Write a ReviewReport to a Markdown file.

    Returns the path to the generated report file.
    """
    os.makedirs(output_dir, exist_ok=True)

    paper_name = os.path.splitext(os.path.basename(report.paper_path))[0]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{paper_name}_review_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)

    content = render_report(report)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
